# SLURM cluster information

rerun-triggers: 
  - mtime
  - code

rerun-incomplete: true

slurm: true

jobs: 300
    
# Default resources per rule. 
default-resources: 
  - tasks=8
  - mem_mb=8000
  - runtime=2880
  - slurm_account="quinlan-rw"
  - slurm_partition="quinlan-shared-rw"

resources: 
  - mem_mb=128000